// Generated by Melange
'use strict';

var Json = require("../src/Json.bs.js");

var data = "\n{\n  \"some\": \"json\", // with a comment!\n  \"more\": [1,3,],\n  /* also\n  multi-line comment */\n  \"this\": {\n    \"object\": {\n      \"is\": {\n        \"really\": \"nested\"\n      }\n    }\n  },\n  \"nested\": [{\n    \"and\": [1,2,{\"stuff\": 5}]\n  }], // trailing commas!\n}\n";

var json = Json.parse(data);

var simple = Json.get("some", json);

var stuff = Json.Infix.$pipe$question$great(Json.Infix.$pipe$question$great(Json.Infix.$pipe$question$great(Json.Infix.$pipe$question$great(Json.Infix.$pipe$question$great(Json.get("nested", json), (function (param) {
                        return Json.nth(0, param);
                      })), (function (param) {
                    return Json.get("and", param);
                  })), (function (param) {
                return Json.nth(2, param);
              })), (function (param) {
            return Json.get("stuff", param);
          })), Json.number);

var nestedString = Json.Infix.$pipe$question$great(Json.getPath("this.object.is.really", json), Json.string);

var str = Json.stringify(json);

console.log(stuff, nestedString);

exports.data = data;
exports.json = json;
exports.simple = simple;
exports.stuff = stuff;
exports.nestedString = nestedString;
exports.str = str;
/* json Not a pure module */
