// Generated by Melange
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var BigList = require("./BigList.bs.js");
var TestLib = require("./TestLib.bs.js");
var DemoTest = require("./DemoTest.bs.js");
var Printexc = require("bs-platform/lib/js/printexc.js");

var match = TestLib.go(undefined);

var report = match[1];

var ensure = match[0];

Printexc.record_backtrace(true);

DemoTest.go(Curry._1(ensure, "DemoTest"));

BigList.go(Curry._1(ensure, "BigList"));

Curry._1(report, undefined);

exports.ensure = ensure;
exports.report = report;
/* match Not a pure module */
