// Generated by Melange
'use strict';

var Stdlib = require("bs-platform/lib/js/stdlib.js");

function go(param) {
  var tests = {
    contents: 0
  };
  var failures = {
    contents: 0
  };
  var ensure = function (group, bool, message) {
    tests.contents = tests.contents + 1 | 0;
    if (!bool) {
      console.log("[" + (group + ("] Failed: " + message)));
      failures.contents = failures.contents + 1 | 0;
      return ;
    }
    
  };
  var report = function (param) {
    Stdlib.print_newline(undefined);
    if (failures.contents === 0) {
      console.log("Success! All " + (String(tests.contents) + " tests passed"));
      return Stdlib.exit(0);
    } else {
      console.log("Failures: " + (String(failures.contents) + (" / " + String(tests.contents))));
      return Stdlib.exit(1);
    }
  };
  return [
          ensure,
          report
        ];
}

exports.go = go;
/* No side effect */
